// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telemetry.Infrastructure.Data;

#nullable disable

namespace Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20251130000659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Telemetry.Domain.Entities.TelemetrySample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Brake")
                        .HasColumnType("REAL");

                    b.Property<bool>("DrsActive")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FuelRemainingKg")
                        .HasColumnType("REAL");

                    b.Property<int>("Gear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpeedKmh")
                        .HasColumnType("REAL");

                    b.Property<float>("Throttle")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<float>("TireTempFL")
                        .HasColumnType("REAL");

                    b.Property<float>("TireTempFR")
                        .HasColumnType("REAL");

                    b.Property<float>("TireTempRL")
                        .HasColumnType("REAL");

                    b.Property<float>("TireTempRR")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TelemetrySamples");
                });
#pragma warning restore 612, 618
        }
    }
}
